version: "3.8"
services:
#  db:
#    image: mysql:5.7
#    container_name: mysql
#    restart: always
#    environment:
#      MYSQL_DATABASE: 'db'
#      MYSQL_ROOT_PASSWORD: 'dbpassword'
#    ports:
#      - '3306:3306'
#    expose:
#      - '3306'
#    healthcheck:
#      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
#      timeout: 20s
#      retries: 10
#    volumes:
#      - ./db_data:/var/lib/mysql
#      - ./db:/docker-entrypoint-initdb.d
#  phpmyadmin:
#    depends_on:
#      - db
#    image: phpmyadmin/phpmyadmin
#    container_name: phpmyadmin
#    restart: always
#    ports:
#      - '8082:80'
#    environment:
#      PMA_HOST: db

  back:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROFILE: docker
    ports:
      - 8080:8080
#    depends_on:
#      db:
#        condition: service_healthy